// Time Complexity : O(n)
// Space Complexity : O(n)
// Did this code successfully run on Leetcode : yes
// Any problem you faced while coding this : no

// Your code here along with comments explaining your approach
/*
We maintain 3 pointers to keep track of the smallest ugly number being generated.Firstly, we start with 1 as
ugly number and keep on generating by multiplying it with 2,3,5 depending upon the minimum value that gets
generated by which pointer and update it accordingly. Lastly, we return the n-1 th value of the array.
 */
class Solution {
    public int nthUglyNumber(int n) {
         int[] arr = new int[n];
         arr[0] = 1;
         int p2 = 0 , p3 = 0 , p5 = 0;

         int n2 = 2, n3 = 3, n5 = 5;

         for(int i = 1 ; i < n ; i++) {
             arr[i] = Math.min(n2, Math.min(n3, n5));

             if(arr[i] == n2) {
                 p2++;
                 n2 = arr[p2] * 2;
             }
             if(arr[i] == n3) {
                 p3++;
                 n3 = arr[p3] * 3;
             }
             if(arr[i] == n5) {
                 p5++;
                 n5 = arr[p5] * 5;
             }
         }
         return arr[n - 1];
    }
}